server:
  port: 8054

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      routes:
        - id: article-service
          uri: lb://article-service
          predicates:
            - Path=article-service
        - id : fournisseur-service
          uri: lb://fournisseur-service
          predicates:
            - Path=/fournisseur/**
        - id : auth-service
          uri: lb://auth-service
          predicates:
            - Path=/v1/**
        - id: facture-service
          uri: lb://facture-service
          predicates:
            - Path=/facture/**
        - id: node-service
          uri: lb://node-service
          predicates:
            - Path=/api/**
        - id: client-service
          uri: lb://livraison-service
          predicates:
            - Path=/livraison-/**

eureka:
  instance:
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
