version: "3.9"
services:
  discovery:
    build:  ../../discovery-server
    ports:
      - "8761:8761"
    image: "discovery-server"

  fournisseur:
    build: ../../Fournisseur
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8800:8800"
    image: "fournisseur-service"

  facture:
    build: ../../Factures
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8880:8880"
    image: "facture-service"
    depends_on:
      - fournisseur

  article:
    build: ../../Article
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8803:8803"
    image: "article-service"
    depends_on:
      - client


     
  gateway:
    build: ../../GatewayServerZuul
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8762:8762"
    image: "gateway-server"

    #http://localhost:8762/categorie-service
    #http://localhost:8762/fournisseur-service
    #http://localhost:8762/factures-service
    #http://localhost:8762/client-service
    #http://localhost:8762/article-service
    #http://localhost:8888/config-server/default
  
