version: "2.2"
services:
  discovery:
    container_name: discovery
    build: ../../discovery-server
    ports:
      - "8761:8761"
    hostname: discovery
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    image: "discovery-server"

  Gateway:
    container_name: GatewayServerZuul
    build: ../../GatewayServerZuul
    ports:
      - "8054:8054"
    hostname: GatewayServerZuul
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    image: "gateway_serverzuul"
    depends_on:
      - discovery-server
  Fournisseur:
    container_name: fournisseur-service
    build: ../../Fournisseur
    ports:
      - "8800:8800"
    hostname: fournisseur
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    image: "candidature-service"
    depends_on:
      - discovery-server

  facture:
    container_name: facture-service
    build: ../../facture-service
    ports:
      - "8880:8880"
    hostname: facture
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    image: "facture-service"
    depends_on:
      - discovery-server

  article:
    container_name: article
    build: ../../Article
    ports:
      - "8085:8085"
    hostname: article
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    image: "article-service"
    depends_on:
      - discovery-server

  Categorie:
    container_name: Categorie-a
    build: ../../categorie-service
    ports:
      - "8086:8086"
    hostname: categorie
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    image: "categorie-service"
    depends_on:
      - discovery-server

  node:
    container_name: node-service
    image: "node-service"
    build: ../../node-service
    ports:
      - "3000:5000"
    hostname: node-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=eureka-server
    depends_on:
      - "Eureka"
      - "Mongo"
    command: "node ./index.js"

  Mongo:
    container_name: Mongo
    image: "mongo:5-focal"
    ports:
      - "27017:27017"
    hostname: mongodb
    depends_on:
      - "discovery-server"